services:
  app:
    container_name: go-highload-app
    build: .
    ports:
      - "8080:8080"
    environment:
      MINIO_ENDPOINT: "minio:9000"
      MINIO_ACCESS_KEY: "minioadmin"
      MINIO_SECRET_KEY: "minioadmin"
      MINIO_USE_SSL: "false"
      MINIO_BUCKET: "go-highload"
    depends_on:
      - minio

  minio:
    image: minio/minio:latest
    container_name: go-highload-minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: "minioadmin"
      MINIO_ROOT_PASSWORD: "minioadmin"
    ports:
      - "9000:9000" # S3 API
      - "9001:9001" # Web-консоль
    volumes:
      - minio-data:/data

volumes:
  minio-data:
